Remove redefinition of StyleProp
Running `tsc` on my project resulted in the following error:

```
node_modules/react-native-web-swiper/index.d.ts:5:5 - error TS2440: Import declaration conflicts with local declaration of 'StyleProp'.

5     StyleProp,
      ~~~~~~~~~
```

This removes the re-definition of StyleProp.